"""Ф1.5 B.2: версионированный NLU-промпт в БД + per-clinic пин.

nlu_prompt — глобальный каталог версий (один на флот, без RLS: не
tenant-данные и не PII). clinic.nlu_prompt_version IS NULL → встроенный
файл prompts/system.md. Staging: пин новой версии сначала на демо-клинику.

Revision ID: 0008
"""
from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE nlu_prompt (
            version int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            body text NOT NULL,
            note text,
            created_at timestamptz NOT NULL DEFAULT now()
        )
    """)
    op.execute("ALTER TABLE clinic ADD COLUMN nlu_prompt_version int "
               "REFERENCES nlu_prompt(version)")
    op.execute("GRANT SELECT, INSERT ON nlu_prompt TO navbat_app")
    op.execute("GRANT USAGE, SELECT ON SEQUENCE nlu_prompt_version_seq TO navbat_app")


def downgrade() -> None:
    op.execute("ALTER TABLE clinic DROP COLUMN IF EXISTS nlu_prompt_version")
    op.execute("DROP TABLE IF EXISTS nlu_prompt")
